imageshare/feed/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from feed.views import HomeView, PostView, DetailPostView

app_name = 'feed'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('post', PostView.as_view(template_name="post.html"), name="post"),
    path('detail/<int:pk>/', DetailPostView.as_view(), name="detail"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imageshare/imageshare/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from feed.views import HomeView, PostView, DetailPostView

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imageshare/feed/models.py
from django.db import models

class Post(models.Model):
    text = models.CharField(max_length=600)
    image = models.ImageField()

    def __str__(self) -> str:
        return self.text

imageshare/feed/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'text',
            'image',
        ]


        

imageshare/feed/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, DetailView

from .models import Post
from .forms import PostForm



class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context
class PostView(FormView):
    template_name = "post.html"
    form_class = PostForm
    success_url = "/" # home, feed

    def form_valid(self, form):
        # form.save() # Why not this?
        Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, "image post successful")
        return super().form_valid(form)



class DetailPostView(DetailView):
    template_name="detail.html"
    model = Post

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['queryset'] = self
    #     return context

imageshare/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Default Title{% endblock title %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" type="text/css" href={% static "content.css" %}>
    </head>
    <body data-bs-theme="dark">

        {% include "includes/navbar.html" %}

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                </li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="container">
            {% block content %}{% endblock content %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </body>
</html>

imageshare/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>Details for Post</h2>
    <img src="{{ post.image.url }}" alt="" class="img-fluid">
     <br>
    {{post}}
{% endblock content %}

imageshare/templates/home.html
{% extends "base.html" %}

{% block title %}Image Sharer - Home{% endblock title %}

{% block content %}

    {% load static %}

    <div class="row">
        {% for post in posts %}
        <div class="col-md-3">
            <div class="card my-4 p-2">
                {% load thumbnail %}
                <img src="{{ post.image|thumbnail_url:'postThumbnail'}}" alt=""> <br>
                {{ post.text }} <br>
                <a href="{% url "feed:detail" post.id %}" class="btn btn-primary">View Details</a>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock content %}

imageshare/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Image Sharer</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "feed:home" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post' %}">Create new post</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

imageshare/templates/post.html
{% extends 'base.html' %}

{% block title %}New Post{% endblock title %}

{% block content %}
    <h2>Upload a new image!</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock content %}